# Generated by Django 4.2.7 on 2023-11-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_scrolls', models.IntegerField()),
                ('screen_time', models.FloatField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
